services:
  mensamax:
    build: .
    image: mensamax-api
    container_name: mensamax-api
    restart: unless-stopped
    env_file: .env
    environment:
      PUBLISH_INTERVAL: "3600"
    volumes:
      - ./data:/data
