version: '3'
services:
  mensamaxapi:
    build:
      context: '.'
      args:
        uid: 1000
    image: mensamaxapi
    ports:
      - 8000:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html

